# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.clockwisemd.com" # the base hostname & protocol for your site
timezone: America/New_York
# future: true

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Clockwise.MD
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Web site for Clockwise.MD" # used by search engines

  # Scripts
  google_analytics: "UA-38490218-1"

# PAGINATION
paginate: 5
paginate_path: "page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

sass:
  sass_dir: _assets
  style: :compressed

gems:
  - jekyll-paginate
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-assets

exclude:
  - vendor
  - README.md
  - .gitignore

assets:
  compress:
    css: true
    js: true

  digest: false

  # cdn: https://www-clockwisemd-com.s3-website-us-east-1.amazonaws.com
  cdn: https://www-base.clockwisemd.com

  assets:
  - "*.png"
  - "*.jpg"
  - "*.eot"
  - "*.svg"
  - "*.ttf"
  - "*.woff"

  sources:
    - _assets/css
    - _assets/img
    - _assets/js
