defaults: &defaults
  docker:
    - image: circleci/ruby:2.5-node-browsers
      environment:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
  working_directory: ~/DocuTAP/www.clockwisemd.com
  shell: /bin/bash --login
  parallelism: 1

version: 2
jobs:
  test:
    <<: *defaults
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
        - v1-dep-
    - run: echo -e "export RAILS_ENV=test\nexport RACK_ENV=test" >> $BASH_ENV
    - run: 'bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
        --jobs=4 --retry=3 '
    - run: bundle exec jekyll build
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ .Revision }}-{{ epoch }}
        paths:
        - vendor/bundle
        - _site
  deploy:
    <<: *defaults
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-{{ .Revision }}-
    - run: echo -e "export RAILS_ENV=test\nexport RACK_ENV=test" >> $BASH_ENV
    - run: 'bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
        --jobs=4 --retry=3 '
    - run 'ls -R _site'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
